In [1]:
import torch
import pandas as pd
import re
import nltk
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer, PorterStemmer
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
nltk.download('punkt_tab')
nltk.download('wordnet')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [31]:
dataset = pd.read_csv("/content/sentiment_analysis.csv")
dataset.head(4)

,Year,Month,Day,Time of Tweet,text,sentiment,Platform
0,2018,8,18,morning,What a great day!!! Looks like dream.,positive,Twitter
1,2018,8,18,noon,"I feel sorry, I miss you here in the sea beach",positive,Facebook
2,2017,8,18,night,Don't angry me,negative,Facebook
3,2022,6,8,morning,We attend in the class just for listening teac...,negative,Facebook

In [32]:
dataset = dataset[["text", "sentiment"]]

In [33]:
dataset.head(3)

                                             text sentiment
0           What a great day!!! Looks like dream.  positive
1  I feel sorry, I miss you here in the sea beach  positive
2                                  Don't angry me  negative

In [34]:
dataset["sentiment"] = dataset["sentiment"].map({
    "positive" : 1,
    "negative" : -1,
    "neutral" : 0
})

In [35]:
dataset["sentiment"]

0      1
1      1
2     -1
3     -1
4     -1
      ..
494   -1
495   -1
496    0
497    1
498   -1
Name: sentiment, Length: 499, dtype: int64

In [36]:
# convert text into emdeding then, apply LSTM on it.

X = dataset["text"]
y = dataset["sentiment"]

In [37]:
stemitization =  PorterStemmer()

def clean(text):

  text =  re.sub(r'[^a-zA-Z0-9 ]', '', text)

  text = text.lower()

  tokens = text.split()

  tokens = [stemitization.stem(token) for token in tokens]


  return tokens

In [38]:
X = X.apply(clean)

In [39]:
dataset["sentiment"].unique()

array([ 1, -1,  0])

In [40]:
# Train test split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [41]:
X_train = X_train.apply(" ".join)
X_test = X_test.apply(" ".join)

In [42]:
# Emmdeding

vectorizor = TfidfVectorizer(max_features=1000, ngram_range=(1, 2))

X_train = vectorizor.fit_transform(X_train)
X_test = vectorizor.transform(X_test)

In [61]:
!pip install xgboost

Requirement already satisfied: xgboost in /usr/local/lib/python3.12/dist-packages (3.2.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.0.2)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.30.7)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from xgboost) (1.16.3)

In [63]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVR
from sklearn.naive_bayes import BernoulliNB
from catboost import CatBoostClassifier
from xgboost import XGBClassifier

In [64]:
lr = LogisticRegression()
svr = SVR()
nb = BernoulliNB()
cb = CatBoostClassifier()
xgb = XGBClassifier()

In [65]:
xgb.fit(X_train, y_train)

ValueError: Invalid classes inferred from unique values of `y`.  Expected: [0 1 2], got [-1  0  1]

In [59]:
print(cb.score(X_test, y_test))

0.62

56    -1
227    1
280    1
486    0
220    1
      ..
106    0
270    0
348   -1
435   -1
102   -1
Name: sentiment, Length: 399, dtype: int64