In [48]:
import torch
import torch.nn as nn
import torch.optim as opt
import pandas as pd
import numpy as np
import re
import nltk
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer, PorterStemmer
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from collections import Counter
nltk.download('punkt_tab')
nltk.download('wordnet')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [15]:
dataset = pd.read_csv("/content/sentiment_analysis.csv")
dataset.head(4)

,Year,Month,Day,Time of Tweet,text,sentiment,Platform
0,2018,8,18,morning,What a great day!!! Looks like dream.,positive,Twitter
1,2018,8,18,noon,"I feel sorry, I miss you here in the sea beach",positive,Facebook
2,2017,8,18,night,Don't angry me,negative,Facebook
3,2022,6,8,morning,We attend in the class just for listening teac...,negative,Facebook

In [16]:
dataset = dataset[["text", "sentiment"]]

In [17]:
dataset.head(3)

                                             text sentiment
0           What a great day!!! Looks like dream.  positive
1  I feel sorry, I miss you here in the sea beach  positive
2                                  Don't angry me  negative

In [18]:
dataset["sentiment"] = dataset["sentiment"].map({
    "positive" : 1,
    "negative" : -1,
    "neutral" : 0
})

In [19]:
dataset["sentiment"]

0      1
1      1
2     -1
3     -1
4     -1
      ..
494   -1
495   -1
496    0
497    1
498   -1
Name: sentiment, Length: 499, dtype: int64

In [20]:
# convert text into emdeding then, apply LSTM on it.

X = dataset["text"]
y = dataset["sentiment"]

In [21]:
stemitization =  PorterStemmer()

def clean(text):

  text =  re.sub(r'[^a-zA-Z0-9 ]', '', text)

  text = text.lower()

  tokens = text.split()

  tokens = [stemitization.stem(token) for token in tokens]


  return tokens

In [22]:
X = X.apply(clean)

In [36]:
# Hyperparameters

vocab_size =  5000
max_length = 100
embed_dim = 100
hidden_dim = 64

In [24]:
dataset["sentiment"].unique()

array([ 1, -1,  0])

In [25]:
# Calculating Vocab Size
all_token = [token for tokens in X for token in tokens]
counter = Counter(all_token).most_common(vocab_size - 2)
word2idx = {'<PAD>': 0, '<UNK>': 1}

for word, _ in counter:
   word2idx[word] = len(word2idx)

vocab_size = len(word2idx)
print(f"Vocabulary size: {vocab_size}")

Vocabulary size: 1291

In [26]:
# Encoding
def Encode(token):
  ids = [word2idx.get(tok, 1) for tok in token]
  if len(ids) >= max_length:
    return ids[:max_length]
  else:
    return ids + [0] * (max_length - len(ids))

# Vectorization
X_encode = np.array([Encode(token) for token in X], dtype = np.int64)
y = y.values.astype(np.float32).reshape(-1,1)

In [29]:
# Train test split

X_train, X_test, y_train, y_test = train_test_split(X_encode, y, test_size = 0.2, random_state = 42)

In [53]:
X_train = torch.tensor(X_train, dtype = torch.long)
X_test = torch.tensor(X_test, dtype = torch.long)
y_train = torch.tensor(y_train, dtype = torch.float32)
y_test = torch.tensor(y_test, dtype = torch.float32)

/tmp/ipykernel_13858/316653357.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_train = torch.tensor(X_train, dtype = torch.long)
/tmp/ipykernel_13858/316653357.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_test = torch.tensor(X_test, dtype = torch.long)
/tmp/ipykernel_13858/316653357.py:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_train = torch.tensor(y_train, dtype = torch.float32)
/tmp/ipykernel_13858/316653357.py:4: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test = torch.tensor(y_test, dtype = torch.float32)

In [54]:
#  LSTM model

class SentimentLSTM(nn.Module):

  def __init__ (self, vocab_size, embed_dim, hidden_dim):
    super().__init__()

    self.emdeding = nn.Embedding(num_embeddings = vocab_size, embedding_dim = embed_dim, padding_idx = 0)
    self.lstm = nn.LSTM(embed_dim, hidden_dim, dropout = 0.2, batch_first = True)
    self.fc = nn.Linear(hidden_dim, 1)

  def forward(self, x):

    x = self.emdeding(x)
    out, _ = self.lstm(x)
    out = out[:,-1,:]
    out = self.fc(out)

    return out

In [55]:
model = SentimentLSTM(vocab_size, embed_dim, hidden_dim)

/usr/local/lib/python3.12/dist-packages/torch/nn/modules/rnn.py:1013: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.2 and num_layers=1
  super().__init__("LSTM", *args, **kwargs)

In [62]:
loss_fn = nn.BCEWithLogitsLoss()
optimizer = opt.Adam(model.parameters(), lr = 0.001)

In [63]:
# Training loop

for epoch in range(100):

  # model.train()

  output = model.forward(X_train)

  loss = loss_fn(output, y_train)

  # Back prop
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

  model.eval()

  with torch.no_grad():
    test_out = model(X_test)
    pred =  (torch.sigmoid(test_out) > 0.5).float()
    acc = (pred == y_test).float().mean().item()


  print(f" {epoch + 1} and the loss is {loss}, and acc is  {acc}")

 1 and the loss is 0.7017106413841248, and acc is  0.3400000035762787
 2 and the loss is 0.6959289908409119, and acc is  0.30000001192092896
 3 and the loss is 0.6901974678039551, and acc is  0.30000001192092896
 4 and the loss is 0.6844958662986755, and acc is  0.30000001192092896
 5 and the loss is 0.6788042783737183, and acc is  0.30000001192092896
 6 and the loss is 0.673093855381012, and acc is  0.30000001192092896
 7 and the loss is 0.6673233509063721, and acc is  0.30000001192092896
 8 and the loss is 0.6614416837692261, and acc is  0.30000001192092896
 9 and the loss is 0.6553908586502075, and acc is  0.30000001192092896
 10 and the loss is 0.6491087079048157, and acc is  0.30000001192092896
 11 and the loss is 0.6425279378890991, and acc is  0.30000001192092896
 12 and the loss is 0.6355744004249573, and acc is  0.30000001192092896
 13 and the loss is 0.6281639337539673, and acc is  0.30000001192092896
 14 and the loss is 0.6201977133750916, and acc is  0.30000001192092896
 15 and the loss is 0.6115562319755554, and acc is  0.30000001192092896
 16 and the loss is 0.602091908454895, and acc is  0.30000001192092896
 17 and the loss is 0.591617226600647, and acc is  0.30000001192092896
 18 and the loss is 0.5798892974853516, and acc is  0.30000001192092896
 19 and the loss is 0.5665836334228516, and acc is  0.30000001192092896
 20 and the loss is 0.5512561202049255, and acc is  0.30000001192092896
 21 and the loss is 0.5332843065261841, and acc is  0.30000001192092896
 22 and the loss is 0.511782169342041, and acc is  0.30000001192092896
 23 and the loss is 0.48550039529800415, and acc is  0.30000001192092896
 24 and the loss is 0.45282113552093506, and acc is  0.30000001192092896
 25 and the loss is 0.41252148151397705, and acc is  0.30000001192092896
 26 and the loss is 0.36746594309806824, and acc is  0.30000001192092896
 27 and the loss is 0.3288802206516266, and acc is  0.30000001192092896
 28 and the loss is 0.3054133355617523, and acc is  0.30000001192092896
 29 and the loss is 0.2946438193321228, and acc is  0.30000001192092896
 30 and the loss is 0.291422039270401, and acc is  0.30000001192092896
 31 and the loss is 0.2920033931732178, and acc is  0.30000001192092896
 32 and the loss is 0.2941534221172333, and acc is  0.30000001192092896
 33 and the loss is 0.2966518998146057, and acc is  0.30000001192092896
 34 and the loss is 0.2988925278186798, and acc is  0.30000001192092896
 35 and the loss is 0.30061957240104675, and acc is  0.30000001192092896
 36 and the loss is 0.30176204442977905, and acc is  0.30000001192092896
 37 and the loss is 0.30234071612358093, and acc is  0.30000001192092896
 38 and the loss is 0.3024194538593292, and acc is  0.30000001192092896
 39 and the loss is 0.30208224058151245, and acc is  0.30000001192092896
 40 and the loss is 0.3014187812805176, and acc is  0.30000001192092896
 41 and the loss is 0.30051857233047485, and acc is  0.30000001192092896
 42 and the loss is 0.29946497082710266, and acc is  0.30000001192092896
 43 and the loss is 0.29833245277404785, and acc is  0.30000001192092896
 44 and the loss is 0.29718613624572754, and acc is  0.30000001192092896
 45 and the loss is 0.29607847332954407, and acc is  0.30000001192092896
 46 and the loss is 0.29505106806755066, and acc is  0.30000001192092896
 47 and the loss is 0.29413360357284546, and acc is  0.30000001192092896
 48 and the loss is 0.2933446764945984, and acc is  0.30000001192092896
 49 and the loss is 0.29269400238990784, and acc is  0.30000001192092896
 50 and the loss is 0.29218190908432007, and acc is  0.30000001192092896
 51 and the loss is 0.29180237650871277, and acc is  0.30000001192092896
 52 and the loss is 0.29154399037361145, and acc is  0.30000001192092896
 53 and the loss is 0.29139113426208496, and acc is  0.30000001192092896
 54 and the loss is 0.29132598638534546, and acc is  0.30000001192092896
 55 and the loss is 0.29132989048957825, and acc is  0.30000001192092896
 56 and the loss is 0.2913840413093567, and acc is  0.30000001192092896
 57 and the loss is 0.29147085547447205, and acc is  0.30000001192092896
 58 and the loss is 0.29157426953315735, and acc is  0.30000001192092896
 59 and the loss is 0.2916809320449829, and acc is  0.30000001192092896
 60 and the loss is 0.29177987575531006, and acc is  0.30000001192092896
 61 and the loss is 0.29186323285102844, and acc is  0.30000001192092896
 62 and the loss is 0.29192572832107544, and acc is  0.30000001192092896
 63 and the loss is 0.2919643819332123, and acc is  0.30000001192092896
 64 and the loss is 0.2919788658618927, and acc is  0.30000001192092896
 65 and the loss is 0.29197001457214355, and acc is  0.30000001192092896
 66 and the loss is 0.2919407784938812, and acc is  0.30000001192092896
 67 and the loss is 0.2918948531150818, and acc is  0.30000001192092896
 68 and the loss is 0.2918362319469452, and acc is  0.30000001192092896
 69 and the loss is 0.29176968336105347, and acc is  0.30000001192092896
 70 and the loss is 0.29169926047325134, and acc is  0.30000001192092896
 71 and the loss is 0.2916286587715149, and acc is  0.30000001192092896
 72 and the loss is 0.29156172275543213, and acc is  0.30000001192092896
 73 and the loss is 0.29150068759918213, and acc is  0.30000001192092896
 74 and the loss is 0.2914479076862335, and acc is  0.30000001192092896
 75 and the loss is 0.29140424728393555, and acc is  0.30000001192092896
 76 and the loss is 0.2913702428340912, and acc is  0.30000001192092896
 77 and the loss is 0.2913459539413452, and acc is  0.30000001192092896
 78 and the loss is 0.29133015871047974, and acc is  0.30000001192092896
 79 and the loss is 0.29132217168807983, and acc is  0.30000001192092896
 80 and the loss is 0.2913203537464142, and acc is  0.30000001192092896
 81 and the loss is 0.2913234531879425, and acc is  0.30000001192092896
 82 and the loss is 0.291329950094223, and acc is  0.30000001192092896
 83 and the loss is 0.29133841395378113, and acc is  0.30000001192092896
 84 and the loss is 0.29134729504585266, and acc is  0.30000001192092896
 85 and the loss is 0.2913556694984436, and acc is  0.30000001192092896
 86 and the loss is 0.2913627624511719, and acc is  0.30000001192092896
 87 and the loss is 0.29136815667152405, and acc is  0.30000001192092896
 88 and the loss is 0.29137158393859863, and acc is  0.30000001192092896
 89 and the loss is 0.29137247800827026, and acc is  0.30000001192092896
 90 and the loss is 0.2913713753223419, and acc is  0.30000001192092896
 91 and the loss is 0.291368693113327, and acc is  0.30000001192092896
 92 and the loss is 0.29136431217193604, and acc is  0.30000001192092896
 93 and the loss is 0.29135897755622864, and acc is  0.30000001192092896
 94 and the loss is 0.29135316610336304, and acc is  0.30000001192092896
 95 and the loss is 0.2913469076156616, and acc is  0.30000001192092896
 96 and the loss is 0.29134100675582886, and acc is  0.30000001192092896
 97 and the loss is 0.2913356125354767, and acc is  0.30000001192092896
 98 and the loss is 0.2913307249546051, and acc is  0.30000001192092896
 99 and the loss is 0.29132694005966187, and acc is  0.30000001192092896
 100 and the loss is 0.2913239896297455, and acc is  0.30000001192092896